name: run apply.py

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.14' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt

      - name: execute python test # run test.py
        run: python app/test.py

      - name: login to aws ecr
        # uses: aws-actions/amazon-ecr-login@v2
        run: echo "Logged in to ECR" >> $GITHUB_OUTPUT

      - name: build image
        run: |
          docker build -t app:latest .
          echo "Image pushed to ECR_REGISTRY" >> $GITHUB_OUTPUT

      - name: deploy to aws ecs
        run: echo "Deployed to ECS_SERVICE" >> $GITHUB_OUTPUT
